### ISSUE TITLE
text_wrap y position

### ISSUE THREAD

**Issue by Hermanverschooten** [andrewtimberlake/elixir-pdf#7]
I have a label on the left and want to have a `text_wrap` next to it.
```elixir
  ...
    |> Pdf.set_font("Helvetica", 8)
    |> Pdf.text_at({28,554}, "korte, duidelijke omschrijving")
    |> Pdf.text_wrap({171,554}, {355, 57}, "geen uren ingevuld op cmr")
```
But if you look in the PDF, 
```
BT
/F1 8 Tf
28 554 Td
(korte, duidelijke omschrijving) Tj
ET
BT
/F1 8 Tf
171 547.956 Td
(geen uren ingevuld op cmr) Tj
ET
```
the y position differs by -4.044.
to get it correctly I need to specify 560.044.

If I change the font size to 10, it becomes 7.555.

**Comment by Hermanverschooten** [comment]
Oh and this is version 0.3.4

**Comment by andrewtimberlake** [comment]
`Pdf.text_at/2` and `Pdf.text_wrap` don’t work together for laying out text next to each other.

`Pdf.text_at/2` uses the `{x,y}` to position the baseline of the text
`Pdf.text_wrap/3` uses the `{x,y}` for the top of the box `{x,y}, {w,h}` and then offsets the text so that it fits within the top of the box.

When I’m doing what you’re trying to do, I do the following:
```
{pdf, :complete} = 
  pdf
  |> Pdf.set_font("Helvetica", 8)
  |> Pdf.text_wrap!({28, 554}, {143, 8}, "korte, duidelijke omschrijving")
  |> Pdf.text_wrap({171,554}, {355, 57}, "geen uren ingevuld op cmr")
```
`148` for `width` was your two `x` offsets `171` - `28`
`8` for `height` is just the font height

**Comment by Hermanverschooten** [comment]
That looks much better. Can you shed some light on how they differ?

**Comment by andrewtimberlake** [comment]
> Pdf.text_at/2 uses the {x,y} to position the baseline of the text
Pdf.text_wrap/3 uses the {x,y} for the top of the box {x,y}, {w,h} and then offsets the text so that it fits within the top of the box.

I added a text positioning example
https://github.com/andrewtimberlake/elixir-pdf/commit/d9034339d32236a02fa61961baa7d216d874fda3
See the results: https://github.com/andrewtimberlake/elixir-pdf/blob/d9034339d32236a02fa61961baa7d216d874fda3/test/output/text_positioning.pdf
